default: &default
  adapter: postgresql
  host: "ec2-54-228-182-57.eu-west-1.compute.amazonaws.com"
  database: "d4mefokkve6lk0"
  port: 5432
  username: "zyfylzxoakbygp"
  password: "a02d40c69893e7149f9cc838c92535bbd07bef50d22d0c3f70e029e2c88f95a9"
  pool: 5
  timeout: 5000

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
