default: &default
  adapter: postgresql
  host: "ec2-54-228-182-57.eu-west-1.compute.amazonaws.com"
  database: "d290qf865sc0d7"
  port: 5432
  username: "loewidjhkattvn"
  password: "7d398f0eb3c6b554935e379de603a0c087296219d8fd359b48af18810d950373"
  pool: 5
  timeout: 5000

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
